---
prometheus-kube-state-metrics:
  - Upgrade kube-state-metrics image to v2.19.1
upgrade:
  - |
    endpointslices are now part of the default resources exposed as metrics.
    endpoints is deprecated and needs to be manually activated through the
    --resources flag.
...
