# Generated by confd
function custom_filters ()
{
{{`{{range ls "/v4"}}`}}{{`{{$data := getv (printf "/v4/%s" .)}}`}}
{{`{{ $data }}`}}
{{`{{end}}`}}

# support any addresses matching our secondary announcements
{{ range .Values.networking.bgp.ipv4.additional_cidrs }}
if ( net ~ {{ . }} ) then { accept; }
{{ end }}

}