# Generated by confd
function custom_filters ()
{
{{`{{range ls "/v6"}}`}}{{`{{$data := getv (printf "/v6/%s" .)}}`}}
{{`{{ $data }}`}}
{{`{{end}}`}}

# support any addresses matching our secondary announcements
{{ range .Values.networking.bgp.ipv6.additional_cidrs }}
if ( net ~ {{ . }} ) then { accept; }
{{ end }}

}