{
 "title": "OpenStack Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "region",
    "query": "label_values(openstack_exporter_cache_refresh_duration_seconds, region)"
   }
  ]
 },
 "panels": [
  { "title": "OpenStack Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Keystone",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "openstack_check_keystone_api{job=\"openstack-metrics\", region=\"$region\"}",
     "function": "last",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ]
    }
   ]
  },
  {
   "title": "Glance",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "openstack_check_glance_api{job=\"openstack-metrics\", region=\"$region\"}",
     "function": "last",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ]
    }
   ]
  },
  {
   "title": "Heat",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "openstack_check_heat_api{job=\"openstack-metrics\", region=\"$region\"}",
     "function": "last",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ]
    }
   ]
  },
  {
   "title": "Neutron",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "openstack_check_neutron_api{job=\"openstack-metrics\", region=\"$region\"}",
     "function": "last",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ]
    }
   ]
  },
  {
   "title": "Nova",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "openstack_check_nova_api{job=\"openstack-metrics\", region=\"$region\"}",
     "function": "last",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ]
    }
   ]
  },
  {
   "title": "Ceph",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "openstack_check_swift_api{job=\"openstack-metrics\", region=\"$region\"}",
     "function": "last",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ]
    }
   ]
  },
  {
   "title": "Cinder",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "openstack_check_cinder_api{job=\"openstack-metrics\", region=\"$region\"}",
     "function": "last",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ]
    }
   ]
  },
  {
   "title": "Placement",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "openstack_check_placement_api{job=\"openstack-metrics\", region=\"$region\"}",
     "function": "last",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ]
    }
   ]
  },
  {
   "title": "RabbitMQ",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "min(rabbitmq_up)",
     "function": "last",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ]
    }
   ]
  },
  {
   "title": "MariaDB",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "min(mysql_global_status_wsrep_ready)",
     "function": "last",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ]
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "sum_over_time(nginx_connections_total{type=\"active\", namespace=\"openstack\"}[5m])",
     "function": "last",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ]
    }
   ]
  },
  {
   "title": "Memcached",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "min(memcached_up)",
     "function": "last",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ]
    }
   ]
  },
  {
   "title": "Disk (used vs total)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 8 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "alias": "free",
     "column": "value",
     "expr": "openstack_total_used_disk_GB{job=\"openstack-metrics\", region=\"$region\"} + openstack_total_free_disk_GB{job=\"openstack-metrics\", region=\"$region\"}",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ]
    },
    {
     "alias": "used",
     "column": "value",
     "expr": "openstack_total_used_disk_GB{job=\"openstack-metrics\", region=\"$region\"}",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ]
    }
   ]
  },
  { "title": "Virtual resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "VCPUs (total vs used)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "free",
     "column": "value",
     "expr": "openstack_total_used_vcpus{job=\"openstack-metrics\", region=\"$region\"} + openstack_total_free_vcpus{job=\"openstack-metrics\", region=\"$region\"}",
     "function": "min",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ]
    },
    {
     "alias": "used",
     "column": "value",
     "expr": "openstack_total_used_vcpus{job=\"openstack-metrics\", region=\"$region\"}",
     "function": "max",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ]
    }
   ]
  },
  {
   "title": "RAM (total vs used)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "alias": "free",
     "column": "value",
     "expr": "openstack_total_used_ram_MB{job=\"openstack-metrics\", region=\"$region\"} + openstack_total_free_ram_MB{job=\"openstack-metrics\", region=\"$region\"}",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ]
    },
    {
     "alias": "used",
     "column": "value",
     "expr": "openstack_total_used_ram_MB{job=\"openstack-metrics\", region=\"$region\"}",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ]
    }
   ]
  },
  {
   "title": "OpenStack Instances",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "free",
     "column": "value",
     "expr": "sum(openstack_running_instances)",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "{{ running_vms }}",
     "refID": "A"
    },
    {
     "alias": "used",
     "column": "value",
     "expr": "sum(openstack_total_running_instances)",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "{{ total_vms }}",
     "refID": "B"
    }
   ]
  }
 ]
}
{
 "title": "Openstack Service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "region",
    "label": "region",
    "query": "label_values(openstack_exporter_cache_refresh_duration_seconds, region)"
   },
   {
    "name": "Service",
    "query": "nova,glance,keystone,cinder,heat,placement,neutron"
   }
  ]
 },
 "panels": [
  { "title": "Service Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "openstack_check_[[Service]]_api{job=\"openstack-metrics\",region=\"$region\"}",
     "function": "last",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ]
    }
   ]
  },
  {
   "title": "HTTP 5xx errors",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "sum(nginx_responses_total{server_zone=~\"[[Service]].*\", status_code=\"5xx\",region=\"$region\"})",
     "function": "count",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ]
    }
   ]
  },
  {
   "title": "HTTP response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_upstream_response_msecs_avg{upstream=~\"openstack-[[Service]].*\",region=\"$region\"}) by (upstream)"
    }
   ]
  },
  {
   "title": "API Availability",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "healthy",
     "column": "value",
     "expr": "openstack_check_[[Service]]_api{region=\"$region\"}",
     "function": "last",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ]
    }
   ]
  },
  {
   "title": "Number of HTTP responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_responses_total{server_zone=~\"[[Service]].*\",region=\"$region\"}) by (status_code)"
    }
   ]
  }
 ]
}