# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Create Trove values file
  copy:
    dest: /tmp/trove.yaml
    content: |
      conf:
        trove:
          DEFAULT:
            default_datastore: mysql

- name: Deploy trove
  include_tasks: _helm_install.yaml
  vars:
    osh_chart: trove
    osh_values_overrides_trove:
      - /tmp/trove.yaml
