# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Deploy Envoy Gateway
  become: false
  block:
    - name: Install Envoy Gateway
      become_user: "{{ kubectl.user }}"
      shell: |
        helm upgrade --install envoy-gateway oci://docker.io/envoyproxy/gateway-helm \
          --version {{ gatewayapi_envoy_version }} \
          --namespace envoy-gateway-system \
          --create-namespace \
          --wait

    - name: Sleep before checking Envoy Gateway pods
      pause:
        seconds: 30

    - name: Wait for Envoy Gateway pods to be ready
      command: kubectl -n envoy-gateway-system wait --timeout=5m --for=condition=Available deployment/envoy-gateway

    - name: Create GatewayClass for Envoy Gateway
      shell: |
        tee > /tmp/gatewayapi_envoy_class.yaml <<EOF
        ---
        apiVersion: gateway.networking.k8s.io/v1
        kind: GatewayClass
        metadata:
          name: default
        spec:
          controllerName: gateway.envoyproxy.io/gatewayclass-controller
        EOF
        kubectl apply -f /tmp/gatewayapi_envoy_class.yaml
