# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Playbook for Horizon deployment.
#
# Usage in zuul.d job definition:
#   run:
#     - playbooks/deploy-env.yaml
#     - playbooks/deploy-horizon.yaml
---
- hosts: primary
  tasks:
    - name: Prepare Kubernetes
      include_role:
        name: deploy-openstack
        tasks_from: prepare-k8s

    - name: Prepare charts
      include_role:
        name: deploy-openstack
        tasks_from: prepare-charts

    - name: Setup OpenStack client
      include_role:
        name: deploy-openstack
        tasks_from: setup-client

    - name: Deploy MariaDB
      include_role:
        name: deploy-openstack
        tasks_from: mariadb

    - name: Deploy Memcached
      include_role:
        name: deploy-openstack
        tasks_from: memcached

    - name: Deploy RabbitMQ
      include_role:
        name: deploy-openstack
        tasks_from: rabbitmq

    - name: Deploy Keystone
      include_role:
        name: deploy-openstack
        tasks_from: keystone

    - name: Deploy Horizon
      include_role:
        name: deploy-openstack
        tasks_from: horizon
