# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
osh_helm_repo: "../openstack-helm"
osh_values_overrides_path: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/../openstack-helm/values_overrides"
osh_values_overrides: []
osh_namespace: openstack
osh_create_namespace: true
osh_helm_timeout: 600
osh_openstack_client_image_tag: 2026.1-ubuntu_noble
osh_helm_tests_tries: 2
osh_test_timeout: 1200

# Octavia defaults
osh_octavia_lb_subnet: "172.31.0.0/24"
osh_octavia_lb_subnet_start: "172.31.0.2"
osh_octavia_lb_subnet_end: "172.31.0.200"
osh_octavia_amphora_image_name: "amphora-x64-haproxy-ubuntu-jammy"
osh_octavia_amphora_image_file: "test-only-amphora-x64-haproxy-ubuntu-jammy.qcow2"
osh_octavia_amphora_image_url: "https://tarballs.opendev.org/openstack/octavia/test-images/test-only-amphora-x64-haproxy-ubuntu-jammy.qcow2"
