{
 "title": "Kubernetes Calico",
 "description": "Calico cluster monitoring dashboard",
 "tags": [ "calico" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Felix",
   "type": "row",
   "gridPos": {
    "h": 1,
    "true": 0,
    "w": 24,
    "x": 0,
    "y": 0
   }
  },
  {
   "title": "Active Local Endpoints",
   "type": "graph",
   "gridPos": {
    "h": 7,
    "true": 1,
    "w": 12,
    "x": 0,
    "y": 1
   },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_active_local_endpoints", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Active Local Policies",
   "type": "graph",
   "gridPos": {
    "h": 7,
    "true": 1,
    "w": 12,
    "x": 12,
    "y": 1
   },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_active_local_policies", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Active Local Selectors",
   "type": "graph",
   "gridPos": {
    "h": 7,
    "true": 8,
    "w": 12,
    "x": 0,
    "y": 8
   },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_active_local_selectors", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Active Local Tags",
   "type": "graph",
   "gridPos": {
    "h": 7,
    "true": 8,
    "w": 12,
    "x": 12,
    "y": 8
   },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_active_local_tags", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Cluster Host Endpoints",
   "type": "graph",
   "gridPos": {
    "h": 7,
    "true": 15,
    "w": 12,
    "x": 0,
    "y": 15
   },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_cluster_num_host_endpoints",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Workload Endpoints",
   "type": "graph",
   "gridPos": {
    "h": 7,
    "true": 15,
    "w": 12,
    "x": 12,
    "y": 15
   },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_cluster_num_workload_endpoints",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Clusters Hosts",
   "type": "graph",
   "gridPos": {
    "h": 7,
    "true": 22,
    "w": 12,
    "x": 0,
    "y": 22
   },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_cluster_num_hosts", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Active IP Sets",
   "type": "graph",
   "gridPos": {
    "h": 7,
    "true": 22,
    "w": 12,
    "x": 12,
    "y": 22
   },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_ipsets_calico", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Active IP Tables Chains",
   "type": "graph",
   "gridPos": {
    "h": 7,
    "true": 29,
    "w": 12,
    "x": 0,
    "y": 29
   },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_iptables_chains", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "IP Set Command Failures",
   "type": "graph",
   "gridPos": {
    "h": 7,
    "true": 29,
    "w": 12,
    "x": 12,
    "y": 29
   },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_ipset_errors", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "IP Tables Save Errors",
   "type": "graph",
   "gridPos": {
    "h": 7,
    "true": 36,
    "w": 12,
    "x": 0,
    "y": 36
   },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_iptables_save_errors", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "IP Tables Restore Errors",
   "type": "graph",
   "gridPos": {
    "h": 7,
    "true": 36,
    "w": 12,
    "x": 12,
    "y": 36
   },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_iptables_restore_errors", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Felix Resyncing Datastore",
   "type": "graph",
   "gridPos": {
    "h": 7,
    "true": 43,
    "w": 12,
    "x": 0,
    "y": 43
   },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_resyncs_started", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Dataplane failed updates",
   "type": "graph",
   "gridPos": {
    "h": 7,
    "true": 43,
    "w": 12,
    "x": 12,
    "y": 43
   },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_int_dataplane_failures", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}