{
 "title": "Ceph - Cluster",
 "description": "Ceph Cluster overview.\r\n",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "ceph_cluster",
    "label": "Cluster",
    "query": "label_values(ceph_health_status, release_group)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_health_status{application=\"ceph\",release_group=\"$ceph_cluster\"}"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_pool_max_avail{application=\"ceph\",release_group=\"$ceph_cluster\"})"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{application=\"ceph\",release_group=\"$ceph_cluster\"}"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{application=\"ceph\",release_group=\"$ceph_cluster\"}"
    }
   ]
  },
  {
   "title": "Current Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes/ceph_cluster_total_bytes{application=\"ceph\",release_group=\"$ceph_cluster\"}"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "OSDs IN",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_osd_in{application=\"ceph\",release_group=\"$ceph_cluster\"})"
    }
   ]
  },
  {
   "title": "OSDs OUT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_osd_metadata{application=\"ceph\",release_group=\"$ceph_cluster\"}) - sum(ceph_osd_in{application=\"ceph\",release_group=\"$ceph_cluster\"})"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_osd_up{application=\"ceph\",release_group=\"$ceph_cluster\"})"
    }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_osd_metadata{application=\"ceph\",release_group=\"$ceph_cluster\"}) - sum(ceph_osd_up{application=\"ceph\",release_group=\"$ceph_cluster\"})"
    }
   ]
  },
  {
   "title": "Average PGs per OSD",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(ceph_osd_numpg{application=\"ceph\",release_group=\"$ceph_cluster\"})"
    }
   ]
  },
  { "title": "CLUSTER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{application=\"ceph\",release_group=\"$ceph_cluster\"} - ceph_cluster_total_used_bytes{application=\"ceph\",release_group=\"$ceph_cluster\"}",
     "legendFormat": "Available"
    },
    { "expr": "ceph_cluster_total_used_bytes", "legendFormat": "Used" },
    { "expr": "ceph_cluster_total_bytes", "legendFormat": "Total Capacity" }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_osd_op_w{application=\"ceph\",release_group=\"$ceph_cluster\"})",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(ceph_osd_op_r{application=\"ceph\",release_group=\"$ceph_cluster\"})",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_osd_op_in_bytes{application=\"ceph\",release_group=\"$ceph_cluster\"})",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(ceph_osd_op_out_bytes{application=\"ceph\",release_group=\"$ceph_cluster\"})",
     "legendFormat": "Read"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Objects in the Cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_cluster_total_objects{application=\"ceph\",release_group=\"$ceph_cluster\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "PGs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_osd_numpg{application=\"ceph\",release_group=\"$ceph_cluster\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(ceph_pg_active{application=\"ceph\",release_group=\"$ceph_cluster\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(ceph_pg_inconsistent{application=\"ceph\",release_group=\"$ceph_cluster\"})",
     "legendFormat": "Inconsistent"
    },
    {
     "expr": "sum(ceph_pg_creating{application=\"ceph\",release_group=\"$ceph_cluster\"})",
     "legendFormat": "Creating"
    },
    {
     "expr": "sum(ceph_pg_recovering{application=\"ceph\",release_group=\"$ceph_cluster\"})",
     "legendFormat": "Recovering"
    },
    {
     "expr": "sum(ceph_pg_down{application=\"ceph\",release_group=\"$ceph_cluster\"})",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Stuck PGs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_pg_degraded{application=\"ceph\",release_group=\"$ceph_cluster\"})",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum(ceph_pg_stale{application=\"ceph\",release_group=\"$ceph_cluster\"})",
     "legendFormat": "Stale"
    },
    {
     "expr": "sum(ceph_pg_undersized{application=\"ceph\",release_group=\"$ceph_cluster\"})",
     "legendFormat": "Undersized"
    }
   ]
  }
 ]
}
{
 "title": "Ceph - OSD",
 "description": "CEPH OSD Status.",
 "tags": [
  "ceph",
  "osd"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "ceph_cluster",
    "label": "Cluster",
    "query": "label_values(ceph_health_status, release_group)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "osd",
    "label": "OSD",
    "query": "label_values(ceph_osd_metadata{release_group=\"$ceph_cluster\"}, ceph_daemon)"
   }
  ]
 },
 "panels": [
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_osd_up{ceph_daemon=\"$osd\",application=\"ceph\",release_group=\"$ceph_cluster\"}"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_osd_in{ceph_daemon=\"$osd\",application=\"ceph\",release_group=\"$ceph_cluster\"}"
    }
   ]
  },
  {
   "title": "Total OSDs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_osd_metadata{application=\"ceph\",release_group=\"$ceph_cluster\"})"
    }
   ]
  },
  { "title": "OSD: $osd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "PGs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_numpg{ceph_daemon=~\"$osd\",application=\"ceph\",release_group=\"$ceph_cluster\"}",
     "legendFormat": "Number of PGs - {{ $osd }}"
    },
    {
     "expr": "avg(ceph_osd_numpg{application=\"ceph\",release_group=\"$ceph_cluster\"})",
     "legendFormat": "Average Number of PGs in the Cluster"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(ceph_osd_stat_bytes_used{ceph_daemon=~\"$osd\",application=\"ceph\",release_group=\"$ceph_cluster\"}/ceph_osd_stat_bytes{ceph_daemon=~\"$osd\",application=\"ceph\",release_group=\"$ceph_cluster\"})*100"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "OSD Storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_stat_bytes_used{ceph_daemon=~\"$osd\",application=\"ceph\",release_group=\"$ceph_cluster\"}",
     "legendFormat": "Used - {{ osd.$osd }}"
    },
    {
     "expr": "ceph_osd_stat_bytes{ceph_daemon=~\"$osd\",application=\"ceph\",release_group=\"$ceph_cluster\"} - ceph_osd_stat_bytes_used{ceph_daemon=~\"$osd\",application=\"ceph\",release_group=\"$ceph_cluster\"}",
     "legendFormat": "Available - {{ $osd }}"
    }
   ]
  },
  {
   "title": "Utilization Variance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(ceph_osd_stat_bytes_used{ceph_daemon=~\"$osd\",application=\"ceph\",release_group=\"$ceph_cluster\"}/ceph_osd_stat_bytes{ceph_daemon=~\"$osd\",application=\"ceph\",release_group=\"$ceph_cluster\"})",
     "legendFormat": "Available - {{ $osd }}"
    }
   ]
  }
 ]
}
{
 "title": "Ceph - Pools",
 "description": "Ceph Pools dashboard.",
 "tags": [
  "ceph",
  "pools"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "ceph_cluster",
    "label": "Cluster",
    "query": "label_values(ceph_health_status, release_group)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "pool",
    "label": "Pool",
    "query": "label_values(ceph_pool_objects{release_group=\"$ceph_cluster\"}, pool_id)"
   },
   {
    "name": "pool_name",
    "label": "Pool",
    "query": "label_values(ceph_pool_metadata{release_group=\"$ceph_cluster\",pool_id=\"[[pool]]\" }, name)"
   }
  ]
 },
 "panels": [
  { "title": "Pool: $pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "[[pool_name]] Pool Storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ceph_pool_max_avail{pool_id=~\"$pool\",application=\"ceph\",release_group=\"$ceph_cluster\"}",
     "legendFormat": "Total - {{ $pool }}"
    },
    {
     "expr": "ceph_pool_bytes_used{pool_id=~\"$pool\",application=\"ceph\",release_group=\"$ceph_cluster\"}",
     "legendFormat": "Used - {{ $pool }}"
    },
    {
     "expr": "ceph_pool_max_avail{pool_id=~\"$pool\",application=\"ceph\",release_group=\"$ceph_cluster\"} - ceph_pool_bytes_used{pool_id=~\"$pool\",application=\"ceph\",release_group=\"$ceph_cluster\"}",
     "legendFormat": "Available - {{ $pool }}"
    },
    {
     "expr": "ceph_pool_raw_bytes_used{pool_id=~\"$pool\",application=\"ceph\",release_group=\"$ceph_cluster\"}",
     "legendFormat": "Raw - {{ $pool }}"
    }
   ]
  },
  {
   "title": "[[pool_name]] Pool Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(ceph_pool_bytes_used{pool_id=~\"$pool\",application=\"ceph\",release_group=\"$ceph_cluster\"} / ceph_pool_max_avail{pool_id=~\"$pool\",application=\"ceph\",release_group=\"$ceph_cluster\"})"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Objects in Pool [[pool_name]]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_pool_objects{pool_id=~\"$pool\",application=\"ceph\",release_group=\"$ceph_cluster\"}",
     "legendFormat": "Objects - {{ $pool_name }}"
    },
    {
     "expr": "ceph_pool_dirty{pool_id=~\"$pool\",application=\"ceph\",release_group=\"$ceph_cluster\"}",
     "legendFormat": "Dirty Objects - {{ $pool_name }}"
    }
   ]
  },
  {
   "title": "[[pool_name]] Pool IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "IOPS" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_pool_rd{pool_id=~\"$pool\",application=\"ceph\",release_group=\"$ceph_cluster\"}[3m])",
     "legendFormat": "Read - {{ $pool_name }}"
    },
    {
     "expr": "irate(ceph_pool_wr{pool_id=~\"$pool\",application=\"ceph\",release_group=\"$ceph_cluster\"}[3m])",
     "legendFormat": "Write - {{ $pool_name }}"
    }
   ]
  },
  {
   "title": "[[pool_name]] Pool Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_pool_rd_bytes{pool_id=\"$pool\",application=\"ceph\",release_group=\"$ceph_cluster\"}[3m])",
     "legendFormat": "Read Bytes - {{ $pool_name }}"
    },
    {
     "expr": "irate(ceph_pool_wr_bytes{pool_id=\"$pool\",application=\"ceph\",release_group=\"$ceph_cluster\"}[3m])",
     "legendFormat": "Written Bytes - {{ $pool_name }}"
    }
   ]
  }
 ]
}