user  nginx;
worker_processes  auto;

error_log  /dev/stdout warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

stream {
    access_log off;

    # Ingress controller proxy (for services not using Gateway API)
    server {
        listen {{ tcpproxy_ingress_openstack_cidr | ipaddr('address') }}:80;
        proxy_pass {{ metallb_ingress_openstack_endpoint_cidr | ipaddr('address') }}:80;
        proxy_bind {{ tcpproxy_ingress_openstack_cidr | ipaddr('address') }} transparent;
    }

    server {
        listen {{ tcpproxy_ingress_openstack_cidr | ipaddr('address') }}:443;
        proxy_pass {{ metallb_ingress_openstack_endpoint_cidr | ipaddr('address') }}:443;
        proxy_bind {{ tcpproxy_ingress_openstack_cidr | ipaddr('address') }} transparent;
    }

    # Gateway API proxy (for services using HTTPRoute)
    server {
        listen {{ tcpproxy_gatewayapi_cidr | ipaddr('address') }}:80;
        proxy_pass {{ metallb_gatewayapi_endpoint_cidr | ipaddr('address') }}:80;
        proxy_bind {{ tcpproxy_gatewayapi_cidr | ipaddr('address') }} transparent;
    }

    server {
        listen {{ tcpproxy_gatewayapi_cidr | ipaddr('address') }}:443;
        proxy_pass {{ metallb_gatewayapi_endpoint_cidr | ipaddr('address') }}:443;
        proxy_bind {{ tcpproxy_gatewayapi_cidr | ipaddr('address') }} transparent;
    }
}
